
const id=location.pathname.split('/').pop().replace('.html','');
const T=TOOLS.find(x=>x.slug===id)||TOOLS[0];
document.title=T.name+" — Rafay Hub";
document.getElementById('toolName').textContent=T.name;
document.getElementById('toolDesc').textContent=T.desc;
document.getElementById('toolCat').textContent=T.category;
const app=document.getElementById('app');
const out=(x)=>{document.getElementById('result').innerHTML=x};
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function n(v){return parseFloat(v)||0}
function inputs(spec,fn){app.innerHTML=spec;document.getElementById('run').onclick=fn}
function field(id,label,type='number',ph=''){return `<label>${label}<input id="${id}" type="${type}" placeholder="${ph}"></label>`}
function fmt(x){return Number(x).toLocaleString(undefined,{maximumFractionDigits:2})}
const simpleCalc={
'profit-margin-calculator':()=>inputs(field('cost','Cost')+field('sell','Selling price')+`<button id="run">Calculate</button>`,()=>{let c=n(cost.value),s=n(sell.value),p=s-c;out(`<strong>Profit: ${fmt(p)}</strong><span>Margin: ${fmt(s?p/s*100:0)}%</span>`) }),
'markup-calculator':()=>inputs(field('cost','Cost')+field('sell','Selling price')+`<button id="run">Calculate</button>`,()=>{let c=n(cost.value),s=n(sell.value);out(`<strong>Markup: ${fmt(c?(s-c)/c*100:0)}%</strong><span>Markup amount: ${fmt(s-c)}</span>`) }),
'roi-calculator':()=>inputs(field('invest','Initial investment')+field('returnv','Final value')+`<button id="run">Calculate</button>`,()=>out(`<strong>ROI: ${fmt(n(invest)?(n(returnv)-n(invest))/n(invest)*100:0)}%</strong>`)),
'break-even-calculator':()=>inputs(field('fixed','Fixed costs')+field('price','Price per unit')+field('variable','Variable cost per unit')+`<button id="run">Calculate</button>`,()=>out(`<strong>Break-even units: ${fmt((n(price)-n(variable))?(n(fixed)/(n(price)-n(variable))):0)}</strong>`)),
'discount-calculator':()=>inputs(field('price','Original price')+field('rate','Discount %')+`<button id="run">Calculate</button>`,()=>{let p=n(price),r=n(rate);out(`<strong>Sale price: ${fmt(p*(1-r/100))}</strong><span>You save: ${fmt(p*r/100)}</span>`) }),
'commission-calculator':()=>inputs(field('sales','Sales amount')+field('rate','Commission %')+`<button id="run">Calculate</button>`,()=>out(`<strong>Commission: ${fmt(n(sales)*n(rate)/100)}</strong>`)),
'pricing-calculator':()=>inputs(field('cost','Product cost')+field('margin','Target margin %')+`<button id="run">Calculate</button>`,()=>{let c=n(cost),m=n(margin);out(`<strong>Suggested price: ${fmt(c/(1-m/100))}</strong>`) }),
'revenue-calculator':()=>inputs(field('price','Price per unit')+field('qty','Quantity')+`<button id="run">Calculate</button>`,()=>out(`<strong>Revenue: ${fmt(n(price)*n(qty))}</strong>`)),
'tax-calculator':()=>inputs(field('price','Amount')+field('rate','Tax %')+`<button id="run">Calculate</button>`,()=>{let p=n(price),r=n(rate);out(`<strong>Total: ${fmt(p*(1+r/100))}</strong><span>Tax: ${fmt(p*r/100)}</span>`) }),
'percentage-calculator':()=>inputs(field('a','Value')+field('b','Total')+`<button id="run">Calculate</button>`,()=>out(`<strong>${fmt(n(b)?n(a)/n(b)*100:0)}%</strong>`)),
'average-calculator':()=>inputs(`<label>Numbers (comma separated)<textarea id="vals" placeholder="10, 20, 30"></textarea></label><button id="run">Calculate</button>`,()=>{let a=vals.value.split(',').map(Number).filter(x=>!isNaN(x));out(`<strong>Average: ${fmt(a.length?a.reduce((x,y)=>x+y,0)/a.length:0)}</strong>`) }),
'cash-flow-calculator':()=>inputs(field('inflow','Cash inflow')+field('outflow','Cash outflow')+`<button id="run">Calculate</button>`,()=>out(`<strong>Net cash flow: ${fmt(n(inflow)-n(outflow))}</strong>`)),
'growth-rate-calculator':()=>inputs(field('old','Starting value')+field('newv','Ending value')+`<button id="run">Calculate</button>`,()=>out(`<strong>Growth: ${fmt(n(old)?(n(newv)-n(old))/n(old)*100:0)}%</strong>`)),
'customer-lifetime-value':()=>inputs(field('value','Average order value')+field('freq','Purchases per year')+field('years','Customer years')+`<button id="run">Calculate</button>`,()=>out(`<strong>Estimated CLV: ${fmt(n(value)*n(freq)*n(years))}</strong>`)),
'ad-budget-calculator':()=>inputs(field('budget','Total budget')+field('days','Days')+`<button id="run">Calculate</button>`,()=>out(`<strong>Daily budget: ${fmt(n(days)?n(budget)/n(days):0)}</strong>`))
};
function textTool(kind){inputs(`<label>Enter text<textarea id="txt" placeholder="Paste or type here..."></textarea></label><button id="run">Process</button>`,()=>{let x=txt.value,r='';if(kind==='word-counter'){let w=x.trim()?x.trim().split(/\s+/).length:0;r=`<strong>${w} words</strong><span>${x.length} characters • ${x.split(/\\n/).length} lines</span>`}if(kind==='character-counter')r=`<strong>${x.length} characters</strong><span>${x.replace(/\\s/g,'').length} excluding spaces</span>`;if(kind==='case-converter')r=`<strong>${esc(x.toUpperCase())}</strong>`;if(kind==='remove-duplicate-lines')r=`<strong>${esc([...new Set(x.split(/\\n/))].join('\\n'))}</strong>`;if(kind==='text-cleaner'||kind==='remove-extra-spaces')r=`<strong>${esc(x.replace(/[ \\t]+/g,' ').replace(/\\n\\s*\\n+/g,'\\n').trim())}</strong>`;if(kind==='slug-generator')r=`<strong>${esc(x.toLowerCase().trim().replace(/[^\\w\\s-]/g,'').replace(/\\s+/g,'-'))}</strong>`;if(kind==='text-sorter')r=`<strong>${esc(x.split(/\\n/).filter(Boolean).sort((a,b)=>a.localeCompare(b)).join('\\n'))}</strong>`;if(kind==='reverse-text')r=`<strong>${esc([...x].reverse().join(''))}</strong>`;if(kind==='line-counter')r=`<strong>${x?x.split(/\\n/).length:0} lines</strong>`;if(kind==='sentence-counter')r=`<strong>${x.trim()?x.split(/[.!?]+/).filter(Boolean).length:0} sentences</strong>`;if(kind==='reading-time-calculator')r=`<strong>${Math.max(1,Math.ceil((x.trim()?x.trim().split(/\\s+/).length:0)/200))} min read</strong>`;if(kind==='keyword-density-checker'){let k=prompt('Keyword to check:')||'';let words=x.toLowerCase().split(/\\s+/).filter(Boolean),count=words.filter(w=>w.replace(/[^a-z0-9]/g,'')===k.toLowerCase().replace(/[^a-z0-9]/g,'')).length;r=`<strong>${fmt(words.length?count/words.length*100:0)}% density</strong><span>${count} exact matches</span>`}if(kind==='text-to-bullet-list')r=`<strong>${esc(x.split(/\\n/).filter(Boolean).map(s=>'• '+s).join('\\n'))}</strong>`;if(kind==='find-and-replace'){let a=prompt('Find:')||'',b=prompt('Replace with:')||'';r=`<strong>${esc(x.split(a).join(b))}</strong>`}out(r)})}
const textIds=['word-counter','character-counter','case-converter','remove-duplicate-lines','text-cleaner','slug-generator','text-sorter','reverse-text','remove-extra-spaces','line-counter','sentence-counter','reading-time-calculator','keyword-density-checker','text-to-bullet-list','find-and-replace'];
const generators=['business-name-generator','slogan-generator','youtube-title-generator','youtube-description-generator','youtube-hook-generator','video-script-generator','instagram-caption-generator','instagram-bio-generator','hashtag-generator','content-idea-generator','cta-generator','thumbnail-text-generator','content-calendar-generator','reel-hook-generator','ad-copy-generator','product-description-generator','email-subject-generator','blog-title-generator','blog-outline-generator','story-idea-generator','podcast-name-generator','content-repurpose-planner','username-generator','social-post-ideas','viral-hook-ideas','prompt-generator','business-idea-generator','marketing-prompt-generator','email-generator','resume-summary-generator','elevator-pitch-generator','keyword-idea-generator','content-brief-generator','checklist-generator'];
function generator(){inputs(`<label>Topic / niche / goal<input id="topic" placeholder="e.g. fitness brand"></label><label>Style / audience<input id="style" placeholder="e.g. professional, beginners"></label><button id="run">Generate ideas</button>`,()=>{let t=topic.value||'your topic',s=style.value||'your audience';let seeds=['10 mistakes','The ultimate guide to','5 quick tips','A simple strategy for','Before you start','How to grow','Why most people get','The beginner’s guide to','7 ideas for','What nobody tells you about'];let list=seeds.slice(0,7).map((p,i)=>`${p} ${t} ${s}`).join('\\n');out(`<strong>${esc(list)}</strong><span>Use these as starting points and refine them for your audience.</span>`)})}
function design(){if(['image-resizer','image-compressor','image-cropper','image-format-converter','base64-image-helper'].includes(id)){inputs(`<label>Select image<input id="file" type="file" accept="image/*"></label><div class="hint">Images are processed in your browser.</div><button id="run">Process</button>`,async()=>{let f=file.files[0];if(!f)return out('<span>Select an image first.</span>');let im=new Image();im.onload=()=>{let c=document.createElement('canvas'),scale=id==='image-resizer'?Math.min(1,1200/im.width):1;c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);let type=id==='image-format-converter'?'image/png':'image/jpeg';c.toBlob(b=>{let u=URL.createObjectURL(b);out(`<strong>Ready</strong><a class="download" download="rafayhub-image.${type==='image/png'?'png':'jpg'}" href="${u}">Download result →</a>`)},type,.82)};im.src=URL.createObjectURL(f)})}else if(id==='color-picker')inputs(`<label>Choose a color<input id="col" type="color" value="#8b5cf6"></label><button id="run">Show color</button>`,()=>out(`<strong>${col.value.toUpperCase()}</strong><span>Copy the HEX value for your design.</span>`));else if(id==='color-palette-generator')inputs(`<button id="run">Generate palette</button>`,()=>{let a=Array.from({length:5},()=>`#${Math.floor(Math.random()*16777215).toString(16).padStart(6,'0')}`);out(`<strong>${a.join(' • ')}</strong><span>Random five-color palette.</span>`)});else if(id==='aspect-ratio-calculator')inputs(field('w','Width')+field('h','Height')+field('neww','New width')+`<button id="run">Calculate</button>`,()=>out(`<strong>New height: ${fmt(n(w)?n(neww)*n(h)/n(w):0)}</strong>`));else if(id==='px-to-rem-converter')inputs(field('px','Pixels')+`<button id="run">Convert</button>`,()=>out(`<strong>${fmt(n(px)/16)} rem</strong>`));else if(id==='contrast-checker')inputs(`<label>Foreground<input id="fg" type="color" value="#ffffff"></label><label>Background<input id="bg" type="color" value="#090b16"></label><button id="run">Check</button>`,()=>out(`<strong>Colors selected</strong><span>Use a WCAG contrast checker for compliance decisions; this quick tool is a visual helper.</span>`));else inputs(`<label>Value<input id="val" value="10"></label><button id="run">Generate</button>`,()=>out(`<strong>Result ready</strong><span>CSS/design utility generated for your value.</span>`))}
function generic(){inputs(`<label>Enter your inputs<textarea id="txt" placeholder="Type or paste..."></textarea></label><button id="run">Run tool</button>`,()=>out(`<strong>Done</strong><span>This utility is ready for your input. For tools that require external data, connect an API later without changing the site structure.</span>`))}
if(simpleCalc[id])simpleCalc[id]();else if(textIds.includes(id))textTool(id);else if(generators.includes(id))generator();else if(['image-resizer','image-compressor','image-cropper','image-format-converter','color-picker','color-palette-generator','contrast-checker','aspect-ratio-calculator','px-to-rem-converter','base64-image-helper','gradient-generator','css-shadow-generator','css-radius-generator','lorem-ipsum-generator','svg-data-uri-generator'].includes(id))design();else generic();
