const id=location.pathname.split('/').pop().replace('.html','');
const T=TOOLS.find(x=>x.slug===id)||TOOLS[0];
document.title=T.name+" — Rafay Hub";
document.getElementById('toolName').textContent=T.name;
document.getElementById('toolDesc').textContent=T.desc;
const app=document.getElementById('app');
const out=(x)=>{document.getElementById('result').innerHTML=x};
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function n(v){return parseFloat(v)||0}
function inputs(spec,fn){app.innerHTML=spec;document.getElementById('run').onclick=fn}
function field(id,label,type='number',ph=''){return `<label>${label}<input id="${id}" type="${type}" placeholder="${ph}"></label>`}
function fmt(x){return Number(x).toLocaleString(undefined,{maximumFractionDigits:2})}
function pct(part,total){return total?part/total*100:0}

const simpleCalc={
'profit-margin-calculator':()=>inputs(field('cost','Cost')+field('sell','Selling price')+`<button id="run">Calculate</button>`,()=>{let c=n(cost.value),s=n(sell.value),p=s-c;out(`<strong>Profit: ${fmt(p)}</strong><span>Margin: ${fmt(pct(p,s))}%</span>`) }),
'markup-calculator':()=>inputs(field('cost','Cost')+field('sell','Selling price')+`<button id="run">Calculate</button>`,()=>{let c=n(cost.value),s=n(sell.value);out(`<strong>Markup: ${fmt(pct(s-c,c))}%</strong><span>Markup amount: ${fmt(s-c)}</span>`) }),
'roi-calculator':()=>inputs(field('invest','Initial investment')+field('returnv','Final value')+`<button id="run">Calculate</button>`,()=>out(`<strong>ROI: ${fmt(pct(n(returnv)-n(invest),n(invest)))}%</strong>`)),
'break-even-calculator':()=>inputs(field('fixed','Fixed costs')+field('price','Price per unit')+field('variable','Variable cost per unit')+`<button id="run">Calculate</button>`,()=>{let m=n(price)-n(variable);out(`<strong>${m>0?`Break-even units: ${fmt(n(fixed)/m)}`:'Price must exceed variable cost.'}</strong>`) }),
'discount-calculator':()=>inputs(field('price','Original price')+field('rate','Discount %')+`<button id="run">Calculate</button>`,()=>{let p=n(price),r=n(rate);out(`<strong>Sale price: ${fmt(p*(1-r/100))}</strong><span>You save: ${fmt(p*r/100)}</span>`) }),
'commission-calculator':()=>inputs(field('sales','Sales amount')+field('rate','Commission %')+`<button id="run">Calculate</button>`,()=>out(`<strong>Commission: ${fmt(n(sales)*n(rate)/100)}</strong>`)),
'pricing-calculator':()=>inputs(field('cost','Product cost')+field('margin','Target margin %')+`<button id="run">Calculate</button>`,()=>{let c=n(cost),m=n(margin);out(`<strong>${m<100?`Suggested price: ${fmt(c/(1-m/100))}`:'Margin must be below 100%.'}</strong>`) }),
'revenue-calculator':()=>inputs(field('price','Price per unit')+field('qty','Quantity')+`<button id="run">Calculate</button>`,()=>out(`<strong>Revenue: ${fmt(n(price)*n(qty))}</strong>`)),
'tax-calculator':()=>inputs(field('price','Amount')+field('rate','Tax %')+`<button id="run">Calculate</button>`,()=>{let p=n(price),r=n(rate);out(`<strong>Total: ${fmt(p*(1+r/100))}</strong><span>Tax: ${fmt(p*r/100)}</span>`) }),
'percentage-calculator':()=>inputs(field('a','Value')+field('b','Total')+`<button id="run">Calculate</button>`,()=>out(`<strong>${fmt(pct(n(a),n(b)))}%</strong>`)),
'average-calculator':()=>inputs(`<label>Numbers (comma separated)<textarea id="vals" placeholder="10, 20, 30"></textarea></label><button id="run">Calculate</button>`,()=>{let a=vals.value.split(',').map(Number).filter(Number.isFinite);out(`<strong>Average: ${fmt(a.length?a.reduce((x,y)=>x+y,0)/a.length:0)}</strong>`) }),
'cash-flow-calculator':()=>inputs(field('inflow','Cash inflow')+field('outflow','Cash outflow')+`<button id="run">Calculate</button>`,()=>out(`<strong>Net cash flow: ${fmt(n(inflow)-n(outflow))}</strong>`)),
'growth-rate-calculator':()=>inputs(field('old','Starting value')+field('newv','Ending value')+`<button id="run">Calculate</button>`,()=>out(`<strong>Growth: ${fmt(pct(n(newv)-n(old),n(old)))}%</strong>`)),
'customer-lifetime-value':()=>inputs(field('value','Average order value')+field('freq','Purchases per year')+field('years','Customer years')+`<button id="run">Calculate</button>`,()=>out(`<strong>Estimated CLV: ${fmt(n(value)*n(freq)*n(years))}</strong>`)),
'ad-budget-calculator':()=>inputs(field('budget','Total budget')+field('days','Days')+`<button id="run">Calculate</button>`,()=>out(`<strong>Daily budget: ${fmt(n(days)?n(budget)/n(days):0)}</strong>`))
};

function textTool(kind){inputs(`<label>Enter text<textarea id="txt" placeholder="Paste or type here..."></textarea></label><button id="run">Process</button>`,()=>{let x=txt.value,r='';
if(kind==='word-counter'){let w=x.trim()?x.trim().split(/\s+/).length:0;r=`<strong>${w} words</strong><span>${x.length} characters • ${x?x.split(/\n/).length:0} lines</span>`}
if(kind==='character-counter')r=`<strong>${x.length} characters</strong><span>${x.replace(/\s/g,'').length} excluding spaces</span>`;
if(kind==='case-converter')r=`<strong>${esc(x.toUpperCase())}</strong>`;
if(kind==='remove-duplicate-lines')r=`<strong>${esc([...new Set(x.split(/\n/))].join('\n'))}</strong>`;
if(kind==='text-cleaner'||kind==='remove-extra-spaces')r=`<strong>${esc(x.replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim())}</strong>`;
if(kind==='slug-generator')r=`<strong>${esc(x.toLowerCase().trim().replace(/[^\w\s-]/g,'').replace(/\s+/g,'-'))}</strong>`;
if(kind==='text-sorter')r=`<strong>${esc(x.split(/\n/).filter(Boolean).sort((a,b)=>a.localeCompare(b)).join('\n'))}</strong>`;
if(kind==='reverse-text')r=`<strong>${esc([...x].reverse().join(''))}</strong>`;
if(kind==='line-counter')r=`<strong>${x?x.split(/\n/).length:0} lines</strong>`;
if(kind==='sentence-counter')r=`<strong>${x.trim()?x.split(/[.!?]+/).filter(Boolean).length:0} sentences</strong>`;
if(kind==='reading-time-calculator')r=`<strong>${Math.max(1,Math.ceil((x.trim()?x.trim().split(/\s+/).length:0)/200))} min read</strong>`;
if(kind==='keyword-density-checker'){let k=prompt('Keyword to check:')||'';let words=x.toLowerCase().split(/\s+/).filter(Boolean),count=words.filter(w=>w.replace(/[^a-z0-9]/g,'')===k.toLowerCase().replace(/[^a-z0-9]/g,'')).length;r=`<strong>${fmt(pct(count,words.length))}% density</strong><span>${count} exact matches</span>`}
if(kind==='text-to-bullet-list')r=`<strong>${esc(x.split(/\n/).filter(Boolean).map(s=>'• '+s).join('\n'))}</strong>`;
if(kind==='find-and-replace'){let a=prompt('Find:')||'',b=prompt('Replace with:')||'';r=`<strong>${esc(x.split(a).join(b))}</strong>`}
out(r)})}
const textIds=['word-counter','character-counter','case-converter','remove-duplicate-lines','text-cleaner','slug-generator','text-sorter','reverse-text','remove-extra-spaces','line-counter','sentence-counter','reading-time-calculator','keyword-density-checker','text-to-bullet-list','find-and-replace'];

function generator(){inputs(`<label>Topic / niche / goal<input id="topic" placeholder="e.g. fitness brand"></label><label>Style / audience<input id="style" placeholder="e.g. professional, beginners"></label><button id="run">Generate suggestions</button>`,()=>{let t=topic.value.trim()||'your topic',s=style.value.trim()||'your audience';let seeds=['10 mistakes','The ultimate guide to','5 quick tips','A simple strategy for','Before you start','How to grow','Why most people get','The beginner’s guide to','7 ideas for','What nobody tells you about'];let list=seeds.slice(0,7).map(p=>`${p} ${t} for ${s}`).join('\n');out(`<strong>${esc(list)}</strong><span>Rule-based suggestions generated in your browser — not claimed to be live search results.</span>`)})}

function businessExtras(){
if(id==='invoice-number-generator')return inputs(`<label>Prefix<input id="prefix" value="INV"></label><label>Number<input id="num" type="number" value="1001"></label><button id="run">Generate</button>`,()=>{let d=new Date(),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;out(`<strong>${esc(prefix.value||'INV')}-${stamp}-${String(Math.max(0,n(num))).padStart(4,'0')}</strong><span>Generated from your inputs and the current browser date.</span>`) });
if(id==='utm-builder')return inputs(`<label>Website URL<input id="url" type="url" placeholder="https://example.com/page"></label><label>Source<input id="source" placeholder="instagram"></label><label>Medium<input id="medium" placeholder="social"></label><label>Campaign<input id="campaign" placeholder="launch"></label><button id="run">Build URL</button>`,()=>{try{let u=new URL(url.value);u.searchParams.set('utm_source',source.value);u.searchParams.set('utm_medium',medium.value);u.searchParams.set('utm_campaign',campaign.value);out(`<strong>${esc(u.toString())}</strong>`)}catch(e){out('<span>Enter a valid full URL, including https://</span>')}})
if(id==='qr-code-generator')return qrTool();
}
function qrTool(){inputs(`<label>Text or URL<textarea id="qrtext" placeholder="https://example.com"></textarea></label><button id="run">Generate QR code</button>`,async()=>{let v=qrtext.value.trim();if(!v)return out('<span>Enter text or a URL first.</span>');out('<span>Generating QR code…</span>');try{if(!window.QRCode){await new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}let data=await QRCode.toDataURL(v,{width:280,margin:2});out(`<strong>QR code ready</strong><div><img alt="QR code" src="${data}" style="max-width:280px;border-radius:12px;background:#fff;padding:10px"></div><a class="download" download="rafayhub-qr.png" href="${data}">Download QR →</a><span>QR generation happens in your browser using the QRCode library.</span>`)}catch(e){out('<span>QR generation failed. Check your internet connection and try again.</span>')}})}

function socialTool(){
if(id==='engagement-rate-calculator'||id==='tiktok-engagement-calculator'||id==='instagram-engagement-calculator')return inputs(field('likes','Likes')+field('comments','Comments')+field('shares','Shares')+field('followers','Followers')+`<button id="run">Calculate</button>`,()=>out(`<strong>Engagement rate: ${fmt(pct(n(likes)+n(comments)+n(shares),n(followers)))}%</strong><span>Calculated from the numbers you entered. No platform data is fabricated.</span>`));
if(id==='youtube-cpm-calculator')return inputs(field('revenue','Revenue (USD)')+field('views','Views')+`<button id="run">Calculate</button>`,()=>out(`<strong>CPM: $${fmt(n(revenue)/Math.max(1,n(views))*1000)}</strong><span>Formula: revenue ÷ views × 1,000.</span>`));
if(id==='youtube-revenue-estimator')return inputs(field('views','Views')+field('rpm','RPM (USD)')+`<button id="run">Estimate</button>`,()=>out(`<strong>Estimated revenue: $${fmt(n(views)/1000*n(rpm))}</strong><span>This is a mathematical estimate based on the RPM you enter, not live YouTube earnings.</span>`));
if(id==='social-media-growth-calculator')return inputs(field('start','Starting followers')+field('end','Ending followers')+field('months','Months')+`<button id="run">Calculate</button>`,()=>{let a=n(start),b=n(end),m=n(months);out(`<strong>Total growth: ${fmt(pct(b-a,a))}%</strong><span>Average net followers/month: ${fmt(m?(b-a)/m:0)}</span>`) });
if(id==='follower-growth-rate')return inputs(field('old','Previous followers')+field('newv','Current followers')+`<button id="run">Calculate</button>`,()=>out(`<strong>Growth rate: ${fmt(pct(n(newv)-n(old),n(old)))}%</strong>`));
if(id==='post-frequency-calculator')return inputs(field('posts','Posts')+field('days','Days')+`<button id="run">Calculate</button>`,()=>out(`<strong>${fmt(n(days)?n(posts)/n(days)*7:0)} posts/week</strong><span>${fmt(n(days)?n(posts)/n(days)*30.4375:0)} posts/month</span>`));
if(id==='social-character-counter'||id==='bio-character-counter')return textTool('character-counter');
if(id==='caption-formatter')return inputs(`<label>Caption<textarea id="txt" placeholder="Paste your caption..."></textarea></label><button id="run">Format</button>`,()=>{let x=txt.value.trim().replace(/\r/g,'');let r=x.split('\n').map(s=>s.trim()).filter(Boolean).join('\n\n');out(`<strong>${esc(r)}</strong><span>Blank lines added for easier social reading.</span>`) });
if(id==='platform-size-guide')return inputs(`<label>Platform<select id="platform"><option>Instagram</option><option>YouTube</option><option>TikTok</option><option>Facebook</option><option>LinkedIn</option></select></label><button id="run">Show sizes</button>`,()=>{let d={Instagram:['Post 1080×1350 (4:5)','Square 1080×1080','Story/Reel 1080×1920'],YouTube:['Thumbnail 1280×720','Shorts 1080×1920'],TikTok:['Video 1080×1920'],Facebook:['Post 1200×630','Story 1080×1920'],LinkedIn:['Post 1200×627','Square 1080×1080']};out(`<strong>${esc(d[platform.value].join('\n'))}</strong><span>Common working dimensions; platform specifications can change.</span>`) });
}

function productivity(){
if(id==='study-plan-generator')return inputs(`<label>Subjects (comma separated)<input id="subjects" placeholder="Math, English, Chemistry"></label><label>Days<input id="days" type="number" value="7"></label><label>Hours/day<input id="hours" type="number" value="2"></label><button id="run">Build plan</button>`,()=>{let a=subjects.value.split(',').map(x=>x.trim()).filter(Boolean),d=Math.max(1,Math.floor(n(days))),h=Math.max(.5,n(hours));if(!a.length)return out('<span>Add at least one subject.</span>');let rows=[];for(let i=0;i<d;i++)rows.push(`Day ${i+1}: ${a[i%a.length]} — ${h} hour${h===1?'':'s'}`);out(`<strong>${esc(rows.join('\n'))}</strong><span>Simple rotating schedule generated from your inputs.</span>`) });
if(id==='pomodoro-timer'||id==='countdown-timer')return timerTool(id==='pomodoro-timer');
if(id==='daily-goal-planner')return inputs(`<label>Top goals<textarea id="goals" placeholder="Finish assignment\nExercise\nRead 20 pages"></textarea></label><button id="run">Create checklist</button>`,()=>out(`<strong>${esc(goals.value.split(/\n/).filter(Boolean).map(x=>'☐ '+x.trim()).join('\n'))}</strong>`));
if(id==='meeting-agenda-generator')return inputs(`<label>Meeting title<input id="title" placeholder="Weekly team meeting"></label><label>Topics<textarea id="topics" placeholder="Project updates\nBlockers\nNext actions"></textarea></label><button id="run">Create agenda</button>`,()=>out(`<strong>${esc((title.value||'Meeting')+'\n\n'+topics.value.split(/\n/).filter(Boolean).map((x,i)=>`${i+1}. ${x.trim()}`).join('\n'))}</strong>`));
if(id==='random-choice-picker')return inputs(`<label>Choices (one per line)<textarea id="choices" placeholder="Option A\nOption B\nOption C"></textarea></label><button id="run">Pick one</button>`,()=>{let a=choices.value.split(/\n/).map(x=>x.trim()).filter(Boolean);out(a.length?`<strong>${esc(a[Math.floor(Math.random()*a.length)])}</strong><span>Randomly selected from your list.</span>`:'<span>Add at least two choices.</span>')});
}

function design(){
if(['image-resizer','image-compressor','image-cropper','image-format-converter','base64-image-helper'].includes(id)){inputs(`<label>Select image<input id="file" type="file" accept="image/*"></label><div class="hint">Images are processed locally in your browser.</div><button id="run">Process</button>`,async()=>{let f=file.files[0];if(!f)return out('<span>Select an image first.</span>');let im=new Image();im.onload=()=>{let c=document.createElement('canvas'),scale=1,w=im.width,h=im.height;
if(id==='image-resizer'){let max=1200;scale=Math.min(1,max/im.width);w=Math.round(im.width*scale);h=Math.round(im.height*scale)}
if(id==='image-cropper'){let target=prompt('Crop ratio, e.g. 1:1 or 4:5','1:1')||'1:1';let [rw,rh]=target.split(':').map(Number);if(rw>0&&rh>0){let tr=rw/rh,ir=im.width/im.height;if(ir>tr){w=Math.round(im.height*tr);h=im.height}else{w=im.width;h=Math.round(im.width/tr)}}}
c.width=w;c.height=h;let ctx=c.getContext('2d');if(id==='image-cropper'){ctx.drawImage(im,(im.width-w)/2,(im.height-h)/2,w,h,0,0,w,h)}else ctx.drawImage(im,0,0,w,h);let type=id==='image-format-converter'?'image/png':'image/jpeg';
if(id==='base64-image-helper'){let reader=new FileReader();reader.onload=()=>out(`<strong>Base64 data URL ready</strong><textarea readonly style="min-height:160px">${esc(reader.result)}</textarea>`);reader.readAsDataURL(f);return}
c.toBlob(b=>{let u=URL.createObjectURL(b);out(`<strong>Result ready</strong><span>${w}×${h}px • ${(b.size/1024).toFixed(1)} KB</span><a class="download" download="rafayhub-image.${type==='image/png'?'png':'jpg'}" href="${u}">Download result →</a>`)},type,.82)};im.onerror=()=>out('<span>Could not read that image.</span>');im.src=URL.createObjectURL(f)})}
else if(id==='color-picker')inputs(`<label>Choose a color<input id="col" type="color" value="#8b5cf6"></label><button id="run">Show color</button>`,()=>{let h=col.value,m=h.match(/[a-f\d]{2}/gi)||[];let rgb=m.map(x=>parseInt(x,16));out(`<strong>${h.toUpperCase()}</strong><span>RGB(${rgb.join(', ')})</span>`) });
else if(id==='color-palette-generator')inputs(`<button id="run">Generate palette</button>`,()=>{let a=Array.from({length:5},()=>`#${Math.floor(Math.random()*16777215).toString(16).padStart(6,'0')}`);out(`<strong>${a.join(' • ')}</strong><span>Random palette generated locally.</span>`)});
else if(id==='aspect-ratio-calculator')inputs(field('w','Width')+field('h','Height')+field('neww','New width')+`<button id="run">Calculate</button>`,()=>out(`<strong>New height: ${fmt(n(w)?n(neww)*n(h)/n(w):0)}</strong>`));
else if(id==='px-to-rem-converter')inputs(field('px','Pixels')+field('base','Root font size (px)')+`<button id="run">Convert</button>`,()=>out(`<strong>${fmt(n(px)/(n(base)||16))} rem</strong>`));
else if(id==='contrast-checker')inputs(`<label>Foreground<input id="fg" type="color" value="#ffffff"></label><label>Background<input id="bg" type="color" value="#090b16"></label><button id="run">Check WCAG ratio</button>`,()=>{function lum(h){let m=h.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4));return .2126*m[0]+.7152*m[1]+.0722*m[2]}let a=lum(fg.value),b=lum(bg.value),r=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);out(`<strong>Contrast ratio: ${r.toFixed(2)}:1</strong><span>${r>=7?'AAA for normal text':r>=4.5?'AA for normal text':r>=3?'AA for large text':'Below WCAG AA thresholds'}</span>`) });
else if(id==='gradient-generator')inputs(`<label>Color 1<input id="c1" type="color" value="#8b5cf6"></label><label>Color 2<input id="c2" type="color" value="#22d3ee"></label><button id="run">Generate CSS</button>`,()=>out(`<strong>linear-gradient(135deg, ${c1.value}, ${c2.value})</strong>`));
else if(id==='css-shadow-generator')inputs(field('x','X offset','number','0')+field('y','Y offset','number','8')+field('blur','Blur','number','24')+field('spread','Spread','number','0')+`<button id="run">Generate CSS</button>`,()=>out(`<strong>box-shadow: ${n(x)}px ${n(y)}px ${n(blur)}px ${n(spread)}px rgba(0,0,0,.18);</strong>`));
else if(id==='css-radius-generator')inputs(field('radius','Radius','number','12')+`<button id="run">Generate CSS</button>`,()=>out(`<strong>border-radius: ${n(radius)}px;</strong>`));
else if(id==='lorem-ipsum-generator')inputs(field('paragraphs','Paragraphs','number','2')+`<button id="run">Generate</button>`,()=>{let p='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna posuere facilisis. Donec sed libero at arcu tincidunt posuere.';out(`<strong>${Array.from({length:Math.min(10,Math.max(1,Math.floor(n(paragraphs)||1)))},()=>esc(p)).join('\n\n')}</strong>`) });
else if(id==='svg-data-uri-generator')inputs(`<label>SVG markup<textarea id="svg" placeholder="<svg ...></svg>"></textarea></label><button id="run">Convert</button>`,()=>out(`<strong>${esc('data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg.value))}</strong>`));
else inputs(`<label>Value<input id="val" value="10"></label><button id="run">Generate</button>`,()=>out(`<strong>Generated from your input: ${esc(val.value)}</strong>`));
}
function timerTool(pomo){let seconds=pomo?25*60:5*60;let interval=null;inputs(`<div id="timer" style="font-size:3rem;font-weight:800;text-align:center">${fmtTime(seconds)}</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="run">Start</button><button id="reset">Reset</button></div><span>${pomo?'25 min focus + 5 min break timer.':'Custom countdown defaulting to 5 minutes.'}</span>`,()=>{if(interval)return;interval=setInterval(()=>{seconds--;document.getElementById('timer').textContent=fmtTime(seconds);if(seconds<=0){clearInterval(interval);interval=null;out('<strong>Time is up.</strong><span>Start again when ready.</span>')}},1000)});document.getElementById('reset').onclick=()=>{clearInterval(interval);interval=null;seconds=pomo?25*60:5*60;document.getElementById('timer').textContent=fmtTime(seconds)};}
function fmtTime(s){s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}

function liveCurrency(){
inputs(`<label>Amount<input id="amount" type="number" value="1" min="0"></label><label>From<select id="from"><option>USD</option><option>EUR</option><option>GBP</option><option>PKR</option><option>JPY</option><option>AUD</option><option>CAD</option><option>AED</option><option>SAR</option><option>INR</option></select></label><label>To<select id="to"><option>PKR</option><option>USD</option><option>EUR</option><option>GBP</option><option>JPY</option><option>AED</option><option>SAR</option><option>INR</option></select></label><button id="run">Get latest rate</button>`,async()=>{let a=n(amount.value);let f=from.value,t=to.value;if(!a)return out('<span>Enter an amount greater than 0.</span>');if(f===t)return out(`<strong>${fmt(a)} ${f} = ${fmt(a)} ${t}</strong><span>Same currency — no conversion needed.</span>`);out('<span>Fetching latest published reference rate…</span>');try{let r=await fetch(`https://api.frankfurter.dev/v2/rate/${f}/${t}`);if(!r.ok)throw new Error('rate');let d=await r.json();out(`<strong>${fmt(a*d.rate)} ${t}</strong><span>1 ${f} = ${d.rate} ${t} • Rate date: ${esc(d.date)}</span><small>Source: Frankfurter reference-rate API. These are latest published reference rates, not live trading quotes.</small>`)}catch(e){out('<span>Could not fetch the current reference rate. Check your internet connection and try again.</span>')}})}
function generic(){out('<strong>This tool needs a more specific input workflow.</strong><span>No fake data is returned. If a tool requires external platform data, it will ask for user-provided figures or an official API.</span>')}

if(simpleCalc[id])simpleCalc[id]();
else if(['invoice-number-generator','utm-builder','qr-code-generator'].includes(id))businessExtras();
else if(textIds.includes(id))textTool(id);
else if(['business-name-generator','slogan-generator','youtube-title-generator','youtube-description-generator','youtube-hook-generator','video-script-generator','instagram-caption-generator','instagram-bio-generator','hashtag-generator','content-idea-generator','cta-generator','thumbnail-text-generator','content-calendar-generator','reel-hook-generator','ad-copy-generator','product-description-generator','email-subject-generator','blog-title-generator','blog-outline-generator','story-idea-generator','podcast-name-generator','content-repurpose-planner','username-generator','social-post-ideas','viral-hook-ideas','prompt-generator','business-idea-generator','marketing-prompt-generator','email-generator','resume-summary-generator','elevator-pitch-generator','keyword-idea-generator','content-brief-generator','checklist-generator'].includes(id))generator();
else if(['engagement-rate-calculator','youtube-cpm-calculator','youtube-revenue-estimator','social-media-growth-calculator','tiktok-engagement-calculator','instagram-engagement-calculator','follower-growth-rate','post-frequency-calculator','social-character-counter','bio-character-counter','caption-formatter','platform-size-guide'].includes(id))socialTool();
else if(['study-plan-generator','pomodoro-timer','countdown-timer','daily-goal-planner','meeting-agenda-generator','random-choice-picker'].includes(id))productivity();
else if(id==='live-currency-converter')liveCurrency();
else if(['image-resizer','image-compressor','image-cropper','image-format-converter','color-picker','color-palette-generator','gradient-generator','contrast-checker','css-shadow-generator','css-radius-generator','lorem-ipsum-generator','svg-data-uri-generator','base64-image-helper','aspect-ratio-calculator','px-to-rem-converter'].includes(id))design();
else generic();
